#syntax
string = "#e4a88a"
constant = "#a95ec9"
"constant.numeric" = "#e4b28f"
"constant.builtin" = "#e4b28f"
variable = "#d55070"
comment = "#26cf98"
special = "#a96ec9"
"punctuation.bracket" = "#a96ec9"
keyword = "#a96ec9"
function = "#24a2ae"
label = "#e4b28f"
type = "#e4b28f"
namespace = "#e4b28f"

#ui
"ui.background" = "background"
"ui.text" = "#d5d8da"
"ui.cursor" = { fg = "background", bg = "dark-pink" }
"ui.cursor.match" = { bg = "selection" }
"ui.gutter" = "#2f3138"
"ui.gutter.selected" = "#797b80"
"ui.window" = "#2f3138"
"ui.selection" = { bg = "selection" }
"diagnostic" = { underlined = { style = "line" } }
"diagnostic.hint" = { underline = { color = "a96ec9", style = "dotted" } }
"diagnostic.info" = { underline = { color = "26cf98", style = "dotted" } }
"diagnostics.error" = { underline = { color = "dark-pink", style = "curl"} }
"diagnostics.warning" = { underline = { color = "e4a88a", style = "curl"} }
"ui.popup" = { bg = "shadow" }
"ui.help" = { bg = "shadow"}
"ui.menu" = { bg = "shadow"}

[palette]
background = "#1c1e26"
shadow = "#16161c"
dark-pink = "#e95378"
selection = "#353747"